CREATE DATABASE company_DB;
USE company_DB;


CREATE TABLE JAV (
    Emp_ID INT PRIMARY KEY,
    Name VARCHAR(50),
    Dept VARCHAR(80),
    Salary INT,
    Age INT
);

INSERT INTO JAV VALUES
(21,'VIGNESH','JAVA',50000,21);
INSERT INTO JAV VALUES
(22,'VIGNESH','JAVA',50000,21);
INSERT INTO JAV VALUES
(23,'VIGNESH','JAVA',50000,21);

SELECT * FROM JAV;

ALTER TABLE JAV 
DROP AGE;

DELETE FROM JAV
WHERE emp_id=1;

TRUNCATE TABLE JAV;
